//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOUND_SYSTEM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Product
    {
        public int Orderno { get; set; }
        public string Product_id { get; set; }
        public Nullable<int> Quanitiy { get; set; }
        public Nullable<int> Price { get; set; }
        public int id { get; set; }
        public Nullable<int> unitprice { get; set; }
        public string Name { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
