//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOUND_SYSTEM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Order_Product = new HashSet<Order_Product>();
        }
    
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Product_id { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual ICollection<Order_Product> Order_Product { get; set; }
    }
}
